

export const IONIC_COMPONENTS = [
  'ion-action-sheet',
  'ion-alert',
  'ion-button',
  'ion-buttons',
  'ion-card',
  'ion-card-content',
  'ion-card-header',
  'ion-card-subtitle',
  'ion-card-title',
  'ion-checkbox',
  'ion-chip',
  'ion-col',
  'ion-content',
  'ion-datetime',
  'ion-fab',
  'ion-footer',
  'ion-grid',
  'ion-header',
  'ion-img',
  'ion-infinite-scroll',
  'ion-infinite-scroll-content',
  'ion-input',
  'ion-item',
  'ion-item-divider',
  'ion-item-group',
  'ion-textarea',
  'ion-radio',
  'ion-radio-group',
  'ion-toolbar',
  'ion-title',
  'ion-router-outlet',
  'ion-nav',
  // TODO the rest
];